### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by Machu95** [macxq/foxess-ha#1]
I can't get this working. I still get following error

Logger: homeassistant.components.sensor
Source: custom_components/foxess_ha/sensor.py:77
Integration: Sensor (documentation, issues)
First occurred: 11:10:26 (1 occurrences)
Last logged: 11:10:26

Error while setting up foxess platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/foxess_ha/sensor.py", line 77, in async_setup_platform
    token = json.loads(restAuth.data)["result"]["token"]
TypeError: 'NoneType' object is not subscriptable

Config like in readme file.

**Comment by BigManDave** [comment]
Same problem here.
Just got my inverter installed today, excited to use your integration but "Unable to login to FoxESS Cloud: {"errno":41807,"result":null}"

Not sure if you're already on the right track but my username also contains capitals, and a dash. Password is all lower case.

**Comment by macxq** [comment]
@BigManDave reach out to me via email, I need your credentials to debug it :)
