### ISSUE TITLE
Integration installation problem

### ISSUE THREAD

**Issue by jok001** [macxq/foxess-ha#106]
Hello

I've looked through the issues posted here and I've seen similar problems but not this specific one so apologies. From the log below it looks like login to foxess cloud is successful but then there doesn't seem to be any data in "allData". I'd be grateful for any suggestions that would solve this.

Thanks in advance.

2023-01-19 13:36:28.723 DEBUG (MainThread) [custom_components.foxess.sensor] Updating data from https://www.foxesscloud.com/
2023-01-19 13:36:28.723 DEBUG (MainThread) [custom_components.foxess.sensor] Token is empty, authenticating for the firts time
2023-01-19 13:36:30.313 DEBUG (MainThread) [custom_components.foxess.sensor] Login succesfull{"errno":0,"result":{"token":"eyJpZCI6ImIyMTZmNTZjLTVkMWYtNGYzYS1hZjU4LTZmZWUzNmU1Nzk2YyIsInNlY3JldCI6IjRmYWM5N2RhYWFiOWI0ZGJiY2Q3M2MxYmFhNmJlZDVlMmI5MWUzNzQ3NDJlOTA1ZjM5M2NkNmVkZTE0MTM1OGMiLCJwYXlsb2FkIjoiVEdzR2lrL0tkVXp3d2x5amRDNnZoaGxUVTNLaTFka0ZHU09UdS9abDhnZzZmVUtqWXgrQllPOE5jSXBTRTlMSHF3VHI0a1RyOTMrWVRCQTY2Y1Z3ZXJBa1J3QWcxam12Ukt2cFBoNWQwdXB0aENXeUJsUDZHVTdKK2RBUWpzckVrdGRJNmcvZUw5ZlZLeldsbXpPSEE5b1lZTVE0SkJZZENtYjJpMHBDSnBqMFFkS2VtbFZPb2xFY3htdjdQRlZqV0Y4WWxuUU1SL2d5cGFUT1l4Y2VzL0ttd2FQNGFvR084aVR0dDV6SFNtRUJtZGRHK28zMCtEMjYxcEZ4MWM0LyJ9","access":1,"user":"XXXXXXXX"}}
2023-01-19 13:36:30.497 DEBUG (MainThread) [custom_components.foxess.sensor] FoxESS Addressbook data fetched correcly {"errno":41930,"result":null}
2023-01-19 13:36:30.497 ERROR (MainThread) [custom_components.foxess.sensor] Unexpected error fetching FoxESS data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 143, in async_update_data
    if int(allData["addressbook"]["result"]["status"]) == 1:
TypeError: 'NoneType' object is not subscriptable

**Comment by macxq** [comment]
{"errno":41930,"result":null} ⟶ incorrect inverter id

**Comment by macxq** [comment]
https://github.com/macxq/foxess-ha/issues/7#issuecomment-962889267

**Comment by jok001** [comment]
Thanks macxq, it's now up and running.
