### ISSUE TITLE
Conected to Foxcloud

### ISSUE THREAD

**Issue by MMark12** [macxq/foxess-ha#115]
I'm having trouble connecting to FoxCloud. In "configuration.yaml" I entered the correct login data (I log in via the website corectly). HA in the logs shows such data as in the attachment
[home-assistant_2023-01-27.log](https://github.com/macxq/foxess-ha/files/10549151/home-assistant_2023-01-27.log)

w configuration.yaml

sensor:
  - platform: foxess
    username: <xxxxxxx>
    password: <xxxxxxxxxxxx>
    deviceID: 601F3620285A007  - in this format because, as you showed in your guide, I do not have such a number like this xxxx-yyyyy-zzzzz, etc.

Please help me because I want to use this integration to control the load via HA.

**Comment by Daibutt** [comment]
When you log in , try copying  the xx-yy-zz from the url as per macxq's screenshot;
![image](https://user-images.githubusercontent.com/69276073/215893825-b7720cda-62a0-4b19-9b66-4b82f4976c2a.png)

**Comment by MMark12** [comment]
![image](https://user-images.githubusercontent.com/123736835/218312902-1e246877-9fad-4966-b61e-f84f1cf31c1f.png)
I couldn't see it in my website

**Comment by MMark12** [comment]
Ok - now I have next errors. Login is OK

2023-02-12 14:23:26.236 DEBUG (MainThread) [custom_components.foxess.sensor] FoxESS Addressbook data fetched correcly {"errno":41930,"result":null}
2023-02-12 14:23:26.237 ERROR (MainThread) [custom_components.foxess.sensor] Unexpected error fetching FoxESS data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 142, in async_update_data
    if int(allData["addressbook"]["result"]["status"]) == 1 or int(allData["addressbook"]["result"]["status"]) == 2:
TypeError: 'NoneType' object is not subscriptable
2023-02-12 14:23:26.261 DEBUG (MainThread) [custom_components.foxess.sensor] Finished fetching FoxESS data in 42.894 seconds (success: False)
2023-02-12 14:23:26.262 ERROR (MainThread) [custom_components.foxess.sensor] FoxESS Cloud initializaction failed, fix error and restar ha

**Comment by macxq** [comment]
@MMark12  
`2023-02-12 14:23:26.236 DEBUG (MainThread) [custom_components.foxess.sensor] FoxESS Addressbook data fetched correcly {"errno":41930,"result":null}`
This error  {"errno":41930,"result":null} is caused by **incorrect inverter id**

**Comment by MMark12** [comment]
Thanks - working :)
