### ISSUE TITLE
KeyError: 'pv1Power'

### ISSUE THREAD

**Issue by iancg** [macxq/foxess-ha#120]
I have v0.19 with a dual hybrid inverter setup.

It works fine for hours/days on end, but intermittently in the logs there is the following;

2023-02-27 01:00:57.239 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 390, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 607, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 466, in state
    value = self.native_value
  File "/config/custom_components/foxess/sensor.py", line 506, in native_value
    return self.coordinator.data["raw"]["pv1Power"]
KeyError: 'pv1Power'

Oddly this appears to happen twice, about one minute past the hour.

[core-ssh config]$ grep -E "Task exception|KeyError" home-assistant.log.1
2023-02-26 14:00:57.519 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
KeyError: 'pv1Power'
2023-02-26 14:00:57.527 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
KeyError: 'pv1Power'
2023-02-26 15:00:57.229 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
KeyError: 'pv1Power'
2023-02-26 15:00:57.233 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
KeyError: 'pv1Power'
2023-02-26 16:00:57.199 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
KeyError: 'pv1Power'
2023-02-26 16:00:57.204 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
KeyError: 'pv1Power'
2023-02-26 16:05:56.714 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
KeyError: 'pv1Power'
2023-02-26 17:00:56.844 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
KeyError: 'pv1Power'
2023-02-26 17:00:56.848 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
KeyError: 'pv1Power'
2023-02-26 18:00:56.743 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
KeyError: 'pv1Power'
2023-02-26 18:00:56.748 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
KeyError: 'pv1Power'
2023-02-26 19:00:57.127 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
KeyError: 'pv1Power'

Outside these errors, I am getting the per-pv data

![image](https://user-images.githubusercontent.com/1828481/221539625-ab3a02df-6bea-4379-8572-895b1469725c.png)

**Comment by webmake** [comment]
Should be fixed with https://github.com/macxq/foxess-ha/pull/161 can you confirm?
