### ISSUE TITLE
RestData.__init__() missing 1 required positional argument: 'verify_ssl'

### ISSUE THREAD

**Issue by frcfrcfrc** [macxq/foxess-ha#144]
After HA update I'm getting error:
Unexpected error fetching FoxESS data: RestData.__init__() missing 1 required positional argument: 'verify_ssl'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 124, in async_update_data
    token = await authAndgetToken(hass, username, hashedPassword)
  File "/config/custom_components/foxess/sensor.py", line 240, in authAndgetToken
    restAuth = RestData(hass, METHOD_POST, _ENDPOINT_AUTH, None,
TypeError: RestData.__init__() missing 1 required positional argument: 'verify_ssl'

**Comment by steveh0553** [comment]
Had error yesterday after update Home assistant 2023.4.0
that error was fixed last night by macqx - Thankyou
However update HA 2023.4.1 this morning has broken FoxESS again .
Tried reinstalling etc, etc now not working :(

**Comment by Sivivatu** [comment]
I have the same issue in my environment after updating  to HA 2023.4.2

```
This error originated from a custom integration.

Logger: custom_components.foxess.sensor
Source: custom_components/foxess/sensor.py:240
Integration: foxess (documentation, issues)
First occurred: 18:40:10 (1 occurrences)
Last logged: 18:40:10

Unexpected error fetching FoxESS data: RestData.__init__() missing 1 required positional argument: 'verify_ssl'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 206, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 124, in async_update_data
    token = await authAndgetToken(hass, username, hashedPassword)
  File "/config/custom_components/foxess/sensor.py", line 240, in authAndgetToken
    restAuth = RestData(hass, METHOD_POST, _ENDPOINT_AUTH, None,
TypeError: RestData.__init__() missing 1 required positional argument: 'verify_ssl'
```

**Comment by Sivivatu** [comment]
I have just updated to the following version details with the same error:
```
Home Assistant 2023.4.5
Supervisor 2023.04.0
Operating System 10.0
Frontend 20230411.1 - latest
```
Is there some additional logs or info that I could provide to help diagnose the issue?
