### ISSUE TITLE
New issue on update (0.21->0.24) "Could not find a suitable TLS CA certificate bundle"

### ISSUE THREAD

**Issue by ryancrim** [macxq/foxess-ha#151]
I have had a working version for a few weeks, and updated today. I'm now seeing the log as below as of updating and restarting HA for the update. I have data up the point of restart.

Versions: 
Running on TrueNAS scale as application
Home Assistant 2022.12.8 Frontend 20221213.1

Unexpected error fetching FoxESS data: Could not find a suitable TLS CA certificate bundle, invalid path: user=X&password=Y

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 125, in async_update_data
    token = await authAndgetToken(hass, username, hashedPassword)
  File "/config/custom_components/foxess/sensor.py", line 244, in authAndgetToken
    await restAuth.async_update()
  File "/usr/src/homeassistant/homeassistant/components/rest/data.py", line 54, in async_update
    self._async_client = get_async_client(
  File "/usr/src/homeassistant/homeassistant/helpers/httpx_client.py", line 36, in get_async_client
    client = hass.data[key] = create_async_httpx_client(hass, verify_ssl)
  File "/usr/src/homeassistant/homeassistant/helpers/httpx_client.py", line 66, in create_async_httpx_client
    client = HassHttpXAsyncClient(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1400, in __init__
    self._transport = self._init_transport(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1448, in _init_transport
    return AsyncHTTPTransport(
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 261, in __init__
    ssl_context = create_ssl_context(verify=verify, cert=cert, trust_env=trust_env)
  File "/usr/local/lib/python3.10/site-packages/httpx/_config.py", line 49, in create_ssl_context
    return SSLConfig(
  File "/usr/local/lib/python3.10/site-packages/httpx/_config.py", line 73, in __init__
    self.ssl_context = self.load_ssl_context()
  File "/usr/local/lib/python3.10/site-packages/httpx/_config.py", line 85, in load_ssl_context
    return self.load_ssl_context_verify()
  File "/usr/local/lib/python3.10/site-packages/httpx/_config.py", line 117, in load_ssl_context_verify
    raise IOError(
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: user=X&password=Y

**Comment by macxq** [comment]
[v0.24](https://github.com/macxq/foxess-ha/tree/v0.24) is not compatible with HA older than 2023.4.0

**Comment by ryancrim** [comment]
Thanks!
