### ISSUE TITLE
 FoxESS Cloud initializaction failed:  Could not find a suitable TLS CA certificate bundle

### ISSUE THREAD

**Issue by Art-L** [macxq/foxess-ha#157]
**Describe the bug**
Hello, Im new to HA community and there's much to learn, but I'm facing some issues on my new integration 
Using Synology NAS and running HA on a docker container.
HA version latest: Home Assistant 2023.3.5
Foxess-ha installed via HACS
getting same issue using Foxess-ha v0.25, 0.24 and master (older versions not tested)

LOGS (password masked by me): 
```
2023-04-16T08:49:36.060118574Z	stdout	[31m2023-04-16 11:49:36.059 ERROR (MainThread) [custom_components.foxess.sensor] FoxESS Cloud initializaction failed, fix error and restar ha[0m
2023-04-16T08:49:36.060064881Z	stdout	OSError: Could not find a suitable TLS CA certificate bundle, invalid path: user=luksas.art&password=***[0m
2023-04-16T08:49:36.060035355Z	stdout	    raise IOError(
2023-04-16T08:49:36.059994171Z	stdout	  File "/usr/local/lib/python3.10/site-packages/httpx/_config.py", line 119, in load_ssl_context_verify
2023-04-16T08:49:36.059933326Z	stdout	    return self.load_ssl_context_verify()
2023-04-16T08:49:36.059890552Z	stdout	  File "/usr/local/lib/python3.10/site-packages/httpx/_config.py", line 87, in load_ssl_context
2023-04-16T08:49:36.059852456Z	stdout	    self.ssl_context = self.load_ssl_context()
2023-04-16T08:49:36.059820268Z	stdout	  File "/usr/local/lib/python3.10/site-packages/httpx/_config.py", line 75, in __init__
2023-04-16T08:49:36.059791908Z	stdout	    return SSLConfig(
2023-04-16T08:49:36.059758386Z	stdout	  File "/usr/local/lib/python3.10/site-packages/httpx/_config.py", line 51, in create_ssl_context
2023-04-16T08:49:36.059717301Z	stdout	    ssl_context = create_ssl_context(verify=verify, cert=cert, trust_env=trust_env)
2023-04-16T08:49:36.059683338Z	stdout	  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 261, in __init__
2023-04-16T08:49:36.059654673Z	stdout	    return AsyncHTTPTransport(
2023-04-16T08:49:36.059620751Z	stdout	  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1448, in _init_transport
2023-04-16T08:49:36.059590192Z	stdout	    self._transport = self._init_transport(
2023-04-16T08:49:36.059541760Z	stdout	  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1400, in __init__
2023-04-16T08:49:36.059510599Z	stdout	    client = HassHttpXAsyncClient(
2023-04-16T08:49:36.059422095Z	stdout	  File "/usr/src/homeassistant/homeassistant/helpers/httpx_client.py", line 67, in create_async_httpx_client
2023-04-16T08:49:36.059383272Z	stdout	    client = hass.data[key] = create_async_httpx_client(hass, verify_ssl)
2023-04-16T08:49:36.059350733Z	stdout	  File "/usr/src/homeassistant/homeassistant/helpers/httpx_client.py", line 37, in get_async_client
2023-04-16T08:49:36.059318821Z	stdout	    self._async_client = get_async_client(
2023-04-16T08:49:36.059272562Z	stdout	  File "/usr/src/homeassistant/homeassistant/components/rest/data.py", line 54, in async_update
2023-04-16T08:49:36.059244360Z	stdout	    await restAuth.async_update()
2023-04-16T08:49:36.059213250Z	stdout	  File "/config/custom_components/foxess/sensor.py", line 245, in authAndgetToken
2023-04-16T08:49:36.059181143Z	stdout	    token = await authAndgetToken(hass, username, hashedPassword)
2023-04-16T08:49:36.059147765Z	stdout	  File "/config/custom_components/foxess/sensor.py", line 125, in async_update_data
2023-04-16T08:49:36.059118960Z	stdout	    return await self.update_method()
2023-04-16T08:49:36.059086350Z	stdout	  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 195, in _async_update_data
2023-04-16T08:49:36.059055309Z	stdout	    self.data = await self._async_update_data()
2023-04-16T08:49:36.059010142Z	stdout	  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
2023-04-16T08:49:36.058949415Z	stdout	Traceback (most recent call last):
2023-04-16T08:49:36.058523009Z	stdout	[31m2023-04-16 11:49:36.055 ERROR (MainThread) [custom_components.foxess.sensor] Unexpected error fetching FoxESS data: Could not find a suitable TLS CA certificate bundle, invalid path: user=luksas.art&password=***
2023-04-16T08:49:33.029813707Z	stdout	[33m2023-04-16 11:49:33.029 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration foxess which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
2023-04-16T08:49:33.029421861Z	stdout	[33m2023-04-16 11:49:33.028 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
2023-04-16T08:49:33.028972412Z	stdout	[33m2023-04-16 11:49:33.028 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration ecovent which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
2023-04-16T08:49:33.028587575Z	stdout	[33m2023-04-16 11:49:33.027 WARNING (SyncWorker_1)
```

**Expected behavior**
foxess-ha should connect to the cloud
**Screenshots**

**Debug logs:**

**HA version:**
2023.3.5

**foxess-ha version:**
 v0.25, 0.24 and master
 
 **UPDATE**
 installing not into docker but in VM (supervised) everything works fine.

**Comment by tezet** [comment]
I have same problem, seems that it started with version v0.24. My installation is on VM.

**Comment by canton7** [comment]
Surely you should put `"homeassistant": "2023.4.0",` in your hacs.json?
