### ISSUE TITLE
KeyError: 'pv1Current'

### ISSUE THREAD

**Issue by webmake** [macxq/foxess-ha#159]
**Describe the bug**
I added additional logging to determine the exact problem and found out why it happens. It turns out that sometimes raw returned empty, so fails `return self.coordinator.data["raw"]["pv1Current"]`

So ` if self.coordinator.data["online"]:` check is insufficient, need to check raw also

**Debug logs:**

```
homeassistant                   | 2023-04-25 15:58:15.243 ERROR (MainThread) [custom_components.foxess.sensor] FoxESSPV1Current
homeassistant                   | 2023-04-25 15:58:15.246 ERROR (MainThread) [custom_components.foxess.sensor] {'report': {'feedin': 0, 'generation': 14.0, 'gridConsumption': 0, 'chargeEnergyToTal': 0, 'dischargeEnergyToTal': 0, 'loads': 0}, 'reportDailyGeneration': {'index': 25, 'value': 16.90000000000009}, 'raw': {'ambientTemperation': 21, 'batChargePower': 0, 'batCurrent': 0, 'batDischargePower': 0, 'batTemperature': 0, 'batVolt': 0, 'boostTemperation': 10, 'chargeEnergyToTal': 0, 'chargeTemperature': 0, 'dischargeEnergyToTal': 0, 'dspTemperature': 0, 'epsCurrentR': 0, 'epsCurrentS': 0, 'epsCurrentT': 0, 'epsPower': 0, 'epsPowerR': 0, 'epsPowerS': 0, 'epsPowerT': 0, 'epsVoltR': 0, 'epsVoltS': 0, 'epsVoltT': 0, 'feedin': 0, 'feedin2': 0, 'feedinPower': 0.413, 'generation': 1414.9, 'generationPower': 0.413, 'gridConsumption': 0, 'gridConsumption2': 0, 'gridConsumptionPower': 0, 'input': 0, 'invBatCurrent': 0, 'invBatPower': 0, 'invBatVolt': 0, 'invTemperation': 10, 'loads': 0, 'loadsPower': 0, 'loadsPowerR': 0, 'loadsPowerS': 0, 'loadsPowerT': 0, 'meterPower': 0, 'meterPower2': 0, 'meterPowerR': 0, 'meterPowerS': 0, 'meterPowerT': 0, 'PowerFactor': 0.83, 'pv1Current': 0.7, 'pv1Power': 0.168, 'pv1Volt': 239.5, 'pv2Current': 0.9, 'pv2Power': 0.222, 'pv2Volt': 246.2, 'pv3Current': 0, 'pv3Power': 0, 'pv3Volt': 0, 'pv4Current': 0, 'pv4Power': 0, 'pv4Volt': 0, 'pvPower': 0.39, 'RCurrent': 0.7, 'ReactivePower': -0.275, 'RFreq': 50, 'RPower': 0.139, 'RVolt': 239.4, 'SCurrent': 0.7, 'SFreq': 50, 'SoC': 0, 'SPower': 0.137, 'SVolt': 236.8, 'TCurrent': 0.7, 'TFreq': 50, 'TPower': 0.137, 'TVolt': 236.1}, 'online': True, 'addressbook': {'errno': 0, 'result': {'deviceSN': 'xxxx', 'plantName': 'xxxxx', 'moduleSN': 'xxxx', 'deviceType': 'T6-G3', 'status': 1, 'country': 'xxxx', 'countryCode': 'xx', 'city': 'xxx', 'address': 'xxx', 'feedinDate': '2022-11-26 09:23:02 EET+0200', 'hardwareVersion': '', 'softVersion': {'master': '1.24', 'slave': '1.00', 'manager': '1.15', 'afci': '0.19'}, 'protocolVersion': 'B1.04.00'}}}
homeassistant                   | 2023-04-25 16:01:16.976 ERROR (MainThread) [custom_components.foxess.sensor] FoxESSPV1Current
homeassistant                   | 2023-04-25 16:01:16.977 ERROR (MainThread) [custom_components.foxess.sensor] {'report': {'feedin': 0, 'generation': 14.0, 'gridConsumption': 0, 'chargeEnergyToTal': 0, 'dischargeEnergyToTal': 0, 'loads': 0}, 'reportDailyGeneration': {'index': 25, 'value': 16.90000000000009}, 'raw': {}, 'online': True, 'addressbook': {'errno': 0, 'result': {'deviceSN': 'xxxx', 'plantName': 'xxxxx', 'moduleSN': 'xxxx', 'deviceType': 'T6-G3', 'status': 1, 'country': 'xxxx', 'countryCode': 'xx', 'city': 'xxx', 'address': 'xxx', 'feedinDate': '2022-11-26 09:23:02 EET+0200', 'hardwareVersion': '', 'softVersion': {'master': '1.24', 'slave': '1.00', 'manager': '1.15', 'afci': '0.19'}, 'protocolVersion': 'B1.04.00'}}}
homeassistant                   | 2023-04-25 16:01:19.317 ERROR (Recorder) [homeassistant] Error doing job: Task exception was never retrieved
homeassistant                   | Traceback (most recent call last):
homeassistant                   |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 193, in _handle_refresh_interval
homeassistant                   |     await self._async_refresh(log_failures=True, scheduled=True)
homeassistant                   |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 341, in _async_refresh
homeassistant                   |     self.async_update_listeners()
homeassistant                   |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 142, in async_update_listeners
homeassistant                   |     update_callback()
homeassistant                   |   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 401, in _handle_coordinator_update
homeassistant                   |     self.async_write_ha_state()
homeassistant                   |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
homeassistant                   |     self._async_write_ha_state()
homeassistant                   |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
homeassistant                   |     state = self._stringify_state(available)
homeassistant                   |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _stringify_state
homeassistant                   |     if (state := self.state) is None:
homeassistant                   |   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 470, in state
homeassistant                   |     value = self.native_value
homeassistant                   |   File "/config/custom_components/foxess/sensor.py", line 557, in native_value
homeassistant                   |     return self.coordinator.data["raw"]["pv1Current"]
homeassistant                   | KeyError: 'pv1Current'
homeassistant                   | 2023-04-25 16:04:18.035 ERROR (MainThread) [custom_components.foxess.sensor] FoxESSPV1Current
homeassistant                   | 2023-04-25 16:04:18.037 ERROR (MainThread) [custom_components.foxess.sensor] {'report': {'feedin': 0, 'generation': 14.0, 'gridConsumption': 0, 'chargeEnergyToTal': 0, 'dischargeEnergyToTal': 0, 'loads': 0}, 'reportDailyGeneration': {'index': 25, 'value': 17}, 'raw': {'ambientTemperation': 21, 'batChargePower': 0, 'batCurrent': 0, 'batDischargePower': 0, 'batTemperature': 0, 'batVolt': 0, 'boostTemperation': 10, 'chargeEnergyToTal': 0, 'chargeTemperature': 0, 'dischargeEnergyToTal': 0, 'dspTemperature': 0, 'epsCurrentR': 0, 'epsCurrentS': 0, 'epsCurrentT': 0, 'epsPower': 0, 'epsPowerR': 0, 'epsPowerS': 0, 'epsPowerT': 0, 'epsVoltR': 0, 'epsVoltS': 0, 'epsVoltT': 0, 'feedin': 0, 'feedin2': 0, 'feedinPower': 0.527, 'generation': 1415, 'generationPower': 0.527, 'gridConsumption': 0, 'gridConsumption2': 0, 'gridConsumptionPower': 0, 'input': 0, 'invBatCurrent': 0, 'invBatPower': 0, 'invBatVolt': 0, 'invTemperation': 10, 'loads': 0, 'loadsPower': 0, 'loadsPowerR': 0, 'loadsPowerS': 0, 'loadsPowerT': 0, 'meterPower': 0, 'meterPower2': 0, 'meterPowerR': 0, 'meterPowerS': 0, 'meterPowerT': 0, 'PowerFactor': 0.89, 'pv1Current': 0.9, 'pv1Power': 0.212, 'pv1Volt': 235.4, 'pv2Current': 1.2, 'pv2Power': 0.292, 'pv2Volt': 243.4, 'pv3Current': 0, 'pv3Power': 0, 'pv3Volt': 0, 'pv4Current': 0, 'pv4Power': 0, 'pv4Volt': 0, 'pvPower': 0.504, 'RCurrent': 0.8, 'ReactivePower': -0.268, 'RFreq': 49.97, 'RPower': 0.17, 'RVolt': 239.8, 'SCurrent': 0.9, 'SFreq': 49.97, 'SoC': 0, 'SPower': 0.189, 'SVolt': 236.6, 'TCurrent': 0.8, 'TFreq': 49.97, 'TPower': 0.168, 'TVolt': 236.7}, 'online': True, 'addressbook': {'errno': 0, 'result': {'deviceSN': 'xxxx', 'plantName': 'xxxxx', 'moduleSN': 'xxxx', 'deviceType': 'T6-G3', 'status': 1, 'country': 'xxxx', 'countryCode': 'xx', 'city': 'xxx', 'address': 'xxx', 'feedinDate': '2022-11-26 09:23:02 EET+0200', 'hardwareVersion': '', 'softVersion': {'master': '1.24', 'slave': '1.00', 'manager': '1.15', 'afci': '0.19'}, 'protocolVersion': 'B1.04.00'}}}
```

**Comment by webmake** [comment]
Solved with https://github.com/macxq/foxess-ha/pull/161
