### ISSUE TITLE
Could not find a suitable TLS CA certificate bundle

### ISSUE THREAD

**Issue by Lemmik112** [macxq/foxess-ha#164]
Hi Guys,

since the update to v0.25 I get the following error:

![image](https://user-images.githubusercontent.com/121201619/235879109-81699477-717e-49cf-8b96-339f8198ae1a.png)

This error originated from a custom integration.

Logger: custom_components.foxess.sensor
Source: helpers/httpx_client.py:66
Integration: foxess (documentation, issues)
First occurred: 9:14:35 AM (1 occurrences)
Last logged: 9:14:35 AM

Unexpected error fetching FoxESS data: Could not find a suitable TLS CA certificate bundle, invalid path: user=XXX&password=XXX
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 125, in async_update_data
    token = await authAndgetToken(hass, username, hashedPassword)
  File "/config/custom_components/foxess/sensor.py", line 245, in authAndgetToken
    await restAuth.async_update()
  File "/usr/src/homeassistant/homeassistant/components/rest/data.py", line 54, in async_update
    self._async_client = get_async_client(
  File "/usr/src/homeassistant/homeassistant/helpers/httpx_client.py", line 36, in get_async_client
    client = hass.data[key] = create_async_httpx_client(hass, verify_ssl)
  File "/usr/src/homeassistant/homeassistant/helpers/httpx_client.py", line 66, in create_async_httpx_client
    client = HassHttpXAsyncClient(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1400, in __init__
    self._transport = self._init_transport(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1448, in _init_transport
    return AsyncHTTPTransport(
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 261, in __init__
    ssl_context = create_ssl_context(verify=verify, cert=cert, trust_env=trust_env)
  File "/usr/local/lib/python3.10/site-packages/httpx/_config.py", line 51, in create_ssl_context
    return SSLConfig(
  File "/usr/local/lib/python3.10/site-packages/httpx/_config.py", line 75, in __init__
    self.ssl_context = self.load_ssl_context()
  File "/usr/local/lib/python3.10/site-packages/httpx/_config.py", line 87, in load_ssl_context
    return self.load_ssl_context_verify()
  File "/usr/local/lib/python3.10/site-packages/httpx/_config.py", line 119, in load_ssl_context_verify
    raise IOError(
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: user=XXX&password=XXX

Home Assistant 2023.1.5 
Supervisor 2023.04.1 
Operating System 10.1 
Frontend 20230110.0 - latest

**Comment by guba91** [comment]
same here, then update to 0.26 and this happened:
`2023-05-09 17:26:16.798 ERROR (MainThread) [homeassistant.config] Platform error: sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 928, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/foxess/sensor.py", line 45, in <module>
    from homeassistant.util.ssl import SSLCipherList
ImportError: cannot import name 'SSLCipherList' from 'homeassistant.util.ssl' (/usr/src/homeassistant/homeassistant/util/ssl.py)`
