### ISSUE TITLE
ImportError: cannot import name 'SSLCipherList' from 'homeassistant.util.ssl' (/usr/src/homeassistant/homeassistant/util/ssl.py)

### ISSUE THREAD

**Issue by dsdann** [macxq/foxess-ha#174]
**Describe the bug**
As of this AM I can't get any data from my foxess HACS

**To Reproduce**
Use version 0.26
Add details to config file
Error getting data

**Expected behavior**
Data is returned

**Screenshots**
N/A

**Debug logs:**

Platform error: sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 928, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/foxess/sensor.py", line 45, in <module>
    from homeassistant.util.ssl import SSLCipherList
ImportError: cannot import name 'SSLCipherList' from 'homeassistant.util.ssl' (/usr/src/homeassistant/homeassistant/util/ssl.py)

**HA version:**
Home Assistant 2023.4.2
Frontend 20230406.1 - latest

**foxess-ha version:**
0.26

**Comment by dsdann** [comment]
Updating to Home Assistant 2023.5.3 has fixed this issue.
