### ISSUE TITLE
integration make HA crash after a day

### ISSUE THREAD

**Issue by guba91** [macxq/foxess-ha#176]
Everything works, but after some time, like a day, HA stop respond and the docker log are full of messages like ValueError: Invalid file descriptor: -1

HA 2023.5.3
foxess-ha version: v0.26

`2023-05-24 15:28:41.500 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.501 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.502 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.502 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.503 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.504 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.504 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.505 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.505 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.506 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.507 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.508 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.508 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.509 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.510 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.510 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.511 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.512 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.512 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.513 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.513 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.514 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.515 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.516 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 256, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/local/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/local/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
2023-05-24 15:28:41.516 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback BaseSelectorEventLoop._start_serving(<aiohttp.web_...x7fd31d92ae30>, <socket.socke...REAM, proto=6>, None, <Server sockets=()>, 128, None)
Traceback (most recent call last):

**Comment by RubenCoppensOnGit** [comment]
Found some problems here that could cause this issue.
What happens in the code when auth token is expired and the properties are refreshed (async)?

in the updateAdressbook method the code doesn't return false if the token is expired. that's one fix i would suggest.
The refershToken counter is never used there (it stays always 0)
and .. what happens when all properties request an update at the same time and the auth token is not valid?
There should be set a lock on the global token if it is updating otherwise the trheads risk to interfere. 
I will try to make some updates locally on this code.. try it .. and let you knw. 
I'm running HA in a container and debugging it during run is a bit difficult there.

**Comment by guba91** [comment]
the problem is that in my home asistant, this integration make it crash completly, in another HA with only this integration it works perfectly.. so there is something somewhere that make it crash.. or is something with the token as @RubenCoppensOnGit said.. because i noticed that every time i open the foxess app to check the data, it broke the token.. 
so maybe is just something like "if token is invalid then re-login"
with https://github.com/mhzawadi/foxess-mqtt same problem with the token, but in the dev-php branch it can see that the token is broken and relogin.. hope this is helpful

**Comment by essenemari** [comment]
Isn't related to #156 but for you crashes in different place?
