### ISSUE TITLE
0.30b makes HA unavailable 

### ISSUE THREAD

**Issue by essenemari** [macxq/foxess-ha#184]
**Describe the bug**
HA stops working and most recent log says it couldn't connect to foxess.

**To Reproduce**
Not sure. Probably blocking access to foxess.

**Expected behavior**
Even if foxess urls are not available, integration shouldn't break HA.

**Debug logs:**

```
2023-07-08 21:55:15.742 ERROR (MainThread) [homeassistant.components.sensor] Pla
tform hacs does not generate unique IDs. ID xxx already exists - ignoring sensor.hacs
...skipping...
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/foxess/sensor.py",
line 492, in getRestData
    response  =  requests.api.get(endpoint_url,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/requests/api.py", line 7
3, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/requests/api.py", line 5
9, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/requests/sessions.py", l
ine 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/requests/sessions.py", l
ine 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/requests/adapters.py", l
ine 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.foxesscloud.co
...skipping...
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection obj
ect at 0xdc876630>, 'Connection to www.foxesscloud.com timed out. (connect timeo
ut=None)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/requests/adapters.py", l
ine 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/urllib3/connectionpool.p
y", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/urllib3/util/retry.py",
line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.foxesscloud.com'
, port=443): Max retries exceeded with url: /c/v0/device/addressbook?deviceID=secret (Caused by ConnectTimeoutError(<urllib3.conne
ction.HTTPSConnection object at 0xdc876630>, 'Connection to www.foxesscloud.com
timed out. (connect timeout=None)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/foxess/sensor.py",
line 492, in getRestData
    response  =  requests.api.get(endpoint_url,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/requests/api.py", line 7
3, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/requests/api.py", line 5
9, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/requests/sessions.py", l
ine 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/requests/sessions.py", l
ine 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/requests/adapters.py", l
ine 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.foxesscloud.co
m', port=443): Max retries exceeded with url: /c/v0/device/addressbook?deviceID=Secret (Caused by ConnectTimeoutError(<urllib3.con
nection.HTTPSConnection object at 0xdc876630>, 'Connection to www.foxesscloud.co
m timed out. (connect timeout=None)'))

```

**HA version:**
2023.7.1 Core on rpi4

**foxess-ha version:**
0.30b

**Comment by essenemari** [comment]
I hit the issue again. It happened around router restart (planned).
Thanks!
