### ISSUE TITLE
Errors in HA log and no sensors visible

### ISSUE THREAD

**Issue by GEL-Barney** [macxq/foxess-ha#279]
**Describe the bug**
I have followed the installation instructions to install using HACS on a docker based HA installation however no sensor data is available (sensors/entities dont show in HA).  One Error and one Warning are shown in the logs:

Error: 
`Platform error: sensor - cannot import name 'UnitOfReactivePower' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)`

Warning:
`Detected blocking call to import_module with args ('custom_components.foxess.sensor',) in /usr/src/homeassistant/homeassistant/loader.py, line 1279: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues`

in configuration.yaml i have:
```
sensor:
  - platform: foxess
    name: Inverter-1
    deviceID: 60JH50203BLD0XX
    deviceSN: 60JH50203BLD0XX
    apiKey: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  - platform: foxess
    name: Inverter-2
    deviceID: 60JH50203BLB1YY
    deviceSN: 60JH50203BLB1YY
    apiKey: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

**To Reproduce**

**Expected behavior**
As an extremely new HA user, I was expecting to see sensors available that I could use to configure both the energy dashboard, and also to be able to add to panels on a dashboard, however no foxess sensors are shown

**Screenshots**

**Debug logs:**
***Error***
Logger: homeassistant.config
Source: config.py:1407
First occurred: 18:04:59 (2 occurrences)
Last logged: 18:04:59

Platform error: sensor - cannot import name 'UnitOfReactivePower' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1407, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1178, in async_get_platforms
    platforms[platform_name] = await future
                               ^^^^^^^^^^^^
ImportError: cannot import name 'UnitOfReactivePower' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

***Warning***
Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 18:04:59 (1 occurrences)
Last logged: 18:04:59

Detected blocking call to import_module with args ('custom_components.foxess.sensor',) in /usr/src/homeassistant/homeassistant/loader.py, line 1279: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config.py", line 1407, in _async_load_and_validate_platform_integration platform = await p_integration.integration.async_get_platform(domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 1083, in async_get_platform platforms = await self.async_get_platforms((platform_name,)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1148, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1073, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1247, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1279, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")

**HA version:**
Core: 2024.7.0
Frontend: 20240703.0

**foxess-ha version:**
v0.43

**Comment by GEL-Barney** [comment]
I have grouped the two log entries together as I believe they are the cause of the integration not working.

As noted above, I am an extremely new user to HA so may be doing something incredibly stupid, and am happy to be wrong about all of this 😆

**Comment by GEL-Barney** [comment]
It appears the latest HA version works as expected
