### ISSUE TITLE
JSON Decoding Error - Issues pulling from FoxESS

### ISSUE THREAD

**Issue by warmfusion** [macxq/foxess-ha#29]
I'm raising this as I've been having a few issues getting data updating from the system. Things _generally_ work, but I suspect the FoxCloud had an update recently as their site was totally down for most of monday.

```

Logger: custom_components.foxess.sensor
Source: custom_components/foxess/sensor.py:153
Integration: foxess (documentation, issues)
First occurred: January 9, 2022, 11:52:40 PM (613 occurrences)
Last logged: 1:02:45 PM
Unexpected error fetching FoxESS data: Expecting value: line 1 column 1 (char 0)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 105, in async_update_data
    token = await authAndgetToken(hass, username, hashedPassword)
  File "/config/custom_components/foxess/sensor.py", line 153, in authAndgetToken
    response = json.loads(restAuth.data)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I'll try and get some more detail on the specific error, but looks like the object response isn't JSON as its failing at the first character?

**Comment by williamjeccles** [comment]
Have you duplicated https://github.com/macxq/foxess-ha/issues/28 might be worth closing and commenting on that related issue

**Comment by warmfusion** [comment]
Yeah, looks like it. Sorry.

I'll see if I can get some more information and add it to the other ticket.

Cheers

**Comment by williamjeccles** [comment]
Could you close this ticket please? you should see the option @warmfusion.
A fix has been added to the other ticket
