### ISSUE TITLE
Dual inverters

### ISSUE THREAD

**Issue by endurasek** [macxq/foxess-ha#66]
I have a problem with reading 2 inverters
I can always read data from only one, but never from two at the same time
![Beaaaz tytułu](https://user-images.githubusercontent.com/103924330/178133436-176d5f42-bedf-4230-a16b-84d7be0669dd.jpg)

**Comment by williamjeccles** [comment]
Are  you using unique username for each? I am and it's working fine.

**Comment by endurasek** [comment]
Yes, foxess1 and foxess2 . Same as in the picture

pon., 11 lip 2022, 14:34 użytkownik William Eccles ***@***.***>
napisał:

**Comment by williamjeccles** [comment]
@endurasek it works if you setup each inverter on it's own end-user account and use unique login details for each inverter.

**Comment by endurasek** [comment]
That's it works. But I have three installations and I would have to create
three accounts?. And I think it should be that you have one account and as
many installations as you want.

sensor:
  - platform: foxess
    username: endurasek
    password: Haslodoserwerafox
    FoxESS1  : 052af7
    FoxESS2 : c19de879-
    FoxESS3 : .....

wt., 19 lip 2022 o 15:00 William Eccles ***@***.***>
napisał(a):

**Comment by macxq** [comment]
@endurasek  fully agree with you that this is how this should looks like.

But I have stuck for some time(months :P) on massive refactor that is to enable new capabilities, i have even create post on https://community.home-assistant.io/t/the-system-cannot-restart-because-the-configuration-is-not-valid-config-schema-definition/425624/8 but even that, did not helped me.

🤔 but the notation that you have proposed  brought me some idea to test!
sensor:
```
  - platform: foxess
    username: endurasek
    password: Haslodoserwerafox
    FoxESS1  : 052af7
    FoxESS2 : c19de879-
    FoxESS3 : .....
```

**Comment by endurasek** [comment]
ok so i'm waiting for some new version  😁

śr., 20 lip 2022 o 09:27 macxq ***@***.***> napisał(a):

**Comment by endurasek** [comment]
Hello

I have an interesting situation ... set up a second foxess account.  And
now I have two inverters registered on the first account, and I don't have
any on the second account, it is empty.  But I have something like this in
my home settings.


Picture below. and I don't know why it started to work! I still have to
test it if the data is not accidental


śr., 20 lip 2022, 22:31 użytkownik Endurasek s ***@***.***>
napisał:

**Comment by macxq** [comment]
@endurasek to get beta version you need to `Redownload` the integration:
<img width="1017" alt="Screenshot 2022-07-22 at 11 53 35" src="https://user-images.githubusercontent.com/2965092/180414722-e5cbb30a-527c-491c-8511-9025c370d8bf.png">
Select  `Show beta version` and then download the last beta version
<img width="825" alt="Screenshot 2022-07-22 at 11 53 50" src="https://user-images.githubusercontent.com/2965092/180414759-52fc9cac-8dd5-40b4-a980-e8b01d61dd3a.png">

❗️ Due to config change - you may need to remove old config before restarting your HA

**Comment by endurasek** [comment]
Now it doesn't work anymore

Logger: homeassistant.setup
Source: custom_components/foxess/__init__.py:85
Integration: foxess (documentation, issues)
First occurred: 07:59:13 (1 occurrences)
Last logged: 07:59:13

Error during setup of component foxess
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/foxess/__init__.py", line 85, in async_setup
    config =  hass_config[DOMAIN]
KeyError: 'foxess'

**Comment by endurasek** [comment]
Logger: homeassistant.setup
Source: setup.py:298
First occurred: 08:11:47 (1 occurrences)
Last logged: 08:11:47

Unable to prepare setup for platform foxess.sensor: Unable to set up component.

**Comment by macxq** [comment]
@endurasek  how does your config looks like ?

**Comment by endurasek** [comment]
- platform: foxess
    name: FoxESS1
    username: endur....
    password: Haslo.....
    deviceID: 052af704-9f08-....
  - platform: foxess
    name: FoxESS2
    username: endur....
    password: Haslo......
    deviceID: c19de879-8860-...

pon., 25 lip 2022 o 10:24 macxq ***@***.***> napisał(a):

**Comment by macxq** [comment]
> ❗️ Due to config change - you may need to remove old config before restarting your HA

staring from v0.2 there is new config format 

https://github.com/macxq/foxess-ha/wiki/New-configuration-format----v0.2

**Comment by macxq** [comment]
In your case it should be:
```yaml
foxess:
  endur....:
    password: Haslo.....
    devices: 
      FoxESS1: 052af704-9f08-....
      FoxESS2: c19de879-8860-...
```

**Comment by endurasek** [comment]
ok so i'll check it out and let it know

pon., 25 lip 2022, 12:13 użytkownik macxq ***@***.***>
napisał:

**Comment by endurasek** [comment]
[image: ha.jpg]

Invalid config for [foxess]: [endurasek] is an invalid option for [foxess].
Check: foxess->endurasek. (See ?, line ?).

pon., 25 lip 2022 o 12:31 Endurasek s ***@***.***> napisał(a):

**Comment by endurasek** [comment]
![ha](https://user-images.githubusercontent.com/103924330/180932272-f31fed25-af11-42d1-b543-c558faa6562b.jpg)

**Comment by macxq** [comment]
are you using [v0.2 ](https://github.com/macxq/foxess-ha/tree/v.0.2.0b)  version ?

**Comment by endurasek** [comment]
Yes


wt., 26 lip 2022, 08:36 użytkownik macxq ***@***.***> napisał:

**Comment by macxq** [comment]
Does it fetch data from both inverters ?

**Comment by endurasek** [comment]
nothing comes.  mi information from ha that the configuration is incorrect

wt., 26 lip 2022, 09:30 użytkownik macxq ***@***.***> napisał:

**Comment by macxq** [comment]
even after forced reboot (eg. via docker restart) ?

**Comment by macxq** [comment]
I know :( working on that!

**Comment by endurasek** [comment]
I went back to version 0.15.
The new version had problems maintaining connection with the server.
And the HA could not be restarted normally.
If you have a new patched version, I will be happy to test it.
