### ISSUE TITLE
Receive 'NoneType' object is not iterable when starting HA  -  better error handling 

### ISSUE THREAD

**Issue by MarcinCalus** [macxq/foxess-ha#7]
I have such issue when HA is starting.
How can I fix it?

2021-11-07 13:39:01 DEBUG (MainThread) [custom_components.foxess.sensor] Login succesfull ...
2021-11-07 13:39:01 DEBUG (MainThread) [custom_components.foxess.sensor] FoxESS Earnings data fetched correcly {"errno":41930,"result":null}
2021-11-07 13:39:01 DEBUG (MainThread) [custom_components.foxess.sensor] FoxESS Addressbook data fetched correcly {"errno":41930,"result":null}
2021-11-07 13:39:01 DEBUG (MainThread) [custom_components.foxess.sensor] FoxESS Raw data fetched correcly {"errno":40261,"result":null} ...
2021-11-07 13:39:01 ERROR (MainThread) [custom_components.foxess.sensor] Unexpected error fetching FoxESS data: 'NoneType' object is not iterab

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/foxess/sensor.py", line 163, in async_update_data
for item in json.loads(restRaw.data)['result']:
TypeError: 'NoneType' object is not iterable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/foxess/sensor.py", line 207, in async_setup_platform
await coordinator.async_config_entry_first_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 161, in async_config_entry_first_refresh
raise ex
homeassistant.exceptions.ConfigEntryNotReady: 'NoneType' object is not iterable

**Comment by macxq** [comment]
I need to improved error handling, here's what need to be handled and propagated with better user message
- `{"errno":41930,"result":null}` ⟶ incorrect inverter id
- `{"errno":40261,"result":null}` ⟶ incorrect inverter id
- `{"errno":41807,"result":null}` ⟶ wrong user name or password


@MarcinCalus you have bad `deviceID` in your config, please make sure that this is exact value from inverter details page address between `=` and `&` character

![Screenshot 2021-11-08 at 08 42 05](https://user-images.githubusercontent.com/2965092/140702734-5dff790f-8100-4b18-b1cc-8dd63cdb8c21.png)

**Comment by MarcinCalus** [comment]
Ahh great works, thank you for help. I wrongly thought i should take inverter sn .

**Comment by rekrutacjaweb** [comment]
@MarcinCalus  i have improved error handling, please close the issue
