### ISSUE TITLE
Does not pass login/retrieve data

### ISSUE THREAD

**Issue by bookofthefuture** [macxq/foxess-ha#76]
Getting this from logs but no data (all 'unknown' except for inverter which returns 'offline'):

2022-09-26 11:18:47.947 DEBUG (MainThread) [custom_components.foxess.sensor] Updating data from https://www.foxesscloud.com/
2022-09-26 11:18:47.947 DEBUG (MainThread) [custom_components.foxess.sensor] Token is empty, authenticating for the firts time

Have checked and rechecked username, password and ID, tried using with and without secrets. No joy so far.

**Comment by macxq** [comment]
do you see on logs?
>  Login succesfull{"errno":0,"result":{"token": 
if not what the next  [custom_components.foxess.sensor] log information

**Comment by bookofthefuture** [comment]
Ah, something has changed. I am now seeing that, which I wasn't earlier. But all my data now showing as 'unavailable' (could be inverter offline?).

Have a new error in the log:

2022-09-26 16:24:05.341 DEBUG (MainThread) [custom_components.foxess.sensor] Finished fetching FoxESS data in 0.340 seconds (success: False)
2022-09-26 16:29:05.000 DEBUG (MainThread) [custom_components.foxess.sensor] Updating data from https://www.foxesscloud.com/
2022-09-26 16:29:05.396 DEBUG (MainThread) [custom_components.foxess.sensor] FoxESS Addressbook data fetched correcly {"errno":41808,"result":null}
2022-09-26 16:29:05.396 ERROR (MainThread) [custom_components.foxess.sensor] Unexpected error fetching FoxESS data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
return await self.update_method()
File "/config/custom_components/foxess/sensor.py", line 143, in async_update_data
if int(allData["addressbook"]["result"]["status"]) == 1:
TypeError: 'NoneType' object is not subscriptable
2022-09-26 16:29:05.401 DEBUG (MainThread) [custom_components.foxess.sensor] Finished fetching FoxESS data in 0.401 seconds (success: False)

**Comment by macxq** [comment]
does this issue exist in the newest version v0.17?
