### ISSUE TITLE
Data pull working and stopping at some point

### ISSUE THREAD

**Issue by ViNYLeq** [macxq/foxess-ha#81]
Hello,
I'm quite fresh user of this integration but having big issues while using. Integration is working but very often stops pulling  the data. Debug mode on and some log entries below. Please help!

Logger: custom_components.foxess.sensor
Source: custom_components/foxess/sensor.py:143
Integration: foxess ([documentation](https://github.com/macxq/foxess-ha), [issues](https://github.com/macxq/foxess-ha/issues))
First occurred: 04:29:32 (46 occurrences)
Last logged: 14:44:48

Unexpected error fetching FoxESS data: 'addressbook'
Unexpected error fetching FoxESS data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 143, in async_update_data
    if int(allData["addressbook"]["result"]["status"]) == 1:
KeyError: 'addressbook'

Logger: custom_components.foxess.sensor
Source: custom_components/foxess/sensor.py:139
Integration: foxess ([documentation](https://github.com/macxq/foxess-ha), [issues](https://github.com/macxq/foxess-ha/issues))
First occurred: 04:29:32 (2 occurrences)
Last logged: 11:04:43

Unable to get Addressbook data from FoxESS Cloud

Logger: homeassistant.components.rest.data
Source: components/rest/data.py:74
Integration: RESTful ([documentation](https://www.home-assistant.io/integrations/rest), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+rest%22))
First occurred: 11:04:43 (1 occurrences)
Last logged: 11:04:43

Timeout while fetching data: https://www.foxesscloud.com/c/v0/device/addressbook?deviceID=xxxxxx

2022-10-11 14:54:48.001 DEBUG (MainThread) [custom_components.foxess.sensor] Updating data from https://www.foxesscloud.com/
2022-10-11 14:54:48.394 DEBUG (MainThread) [custom_components.foxess.sensor] FoxESS Addressbook data fetched correcly {"errno":41808,"result":null}
2022-10-11 14:54:48.394 ERROR (MainThread) [custom_components.foxess.sensor] Unexpected error fetching FoxESS data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
return await self.update_method()
File "/config/custom_components/foxess/sensor.py", line 143, in async_update_data
if int(allData["addressbook"]["result"]["status"]) == 1:
TypeError: 'NoneType' object is not subscriptable

**Comment by bagienny** [comment]
I have the same issue and I just got it to work today.

**Comment by macxq** [comment]
does this issue exist in the newest version v0.17?
