### ISSUE TITLE
Unexpected error fetching FoxESS data since upgrading to Home Assistant Core 2022.11.0

### ISSUE THREAD

**Issue by Grimroper** [macxq/foxess-ha#86]
Since upgrading to Home Assistant Core 2022.11.0 the Foxess-ha integration is failing to connect.  Its reporting an error "Unexpected error fetching FoxESS data: Attempted to send an sync request with an AsyncClient instance."

```
This error originated from a custom integration.

Logger: custom_components.foxess.sensor
Source: components/rest/data.py:63
Integration: foxess (documentation, issues)
First occurred: 12:01:32 (1 occurrences)
Last logged: 12:01:32

Unexpected error fetching FoxESS data: Attempted to send an sync request with an AsyncClient instance.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 123, in async_update_data
    token = await authAndgetToken(hass, username, hashedPassword)
  File "/config/custom_components/foxess/sensor.py", line 194, in authAndgetToken
    await restAuth.async_update()
  File "/usr/src/homeassistant/homeassistant/components/rest/data.py", line 63, in async_update
    response = await self._async_client.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1711, in _send_single_request
    raise RuntimeError(
RuntimeError: Attempted to send an sync request with an AsyncClient instance.
```

Issue persists after restarts and having upgraded to Core 2022.11.01.  Issue wasnt present in 2022.10.5 which I have restored back to and can confirm its working as expected.

Full log details are

```
2022-11-04 12:01:32.028 ERROR (MainThread) [custom_components.foxess.sensor] Unexpected error fetching FoxESS data: Attempted to send an sync request with an AsyncClient instance.
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
return await self.update_method()
File "/config/custom_components/foxess/sensor.py", line 123, in async_update_data
token = await authAndgetToken(hass, username, hashedPassword)
File "/config/custom_components/foxess/sensor.py", line 194, in authAndgetToken
await restAuth.async_update()
File "/usr/src/homeassistant/homeassistant/components/rest/data.py", line 63, in async_update
response = await self._async_client.request(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
return await self.send(request, auth=auth, follow_redirects=follow_redirects)
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1614, in send
response = await self._send_handling_auth(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
response = await self._send_handling_redirects(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
response = await self._send_single_request(request)
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1711, in _send_single_request
raise RuntimeError(
RuntimeError: Attempted to send an sync request with an AsyncClient instance.
2022-11-04 12:01:32.039 ERROR (MainThread) [custom_components.foxess.sensor] FoxESS Cloud initializaction failed, fix error and restar ha
```

**Comment by Grimroper** [comment]
Closing as duplicate of #83

**Comment by Grimroper** [comment]
.
