### ISSUE TITLE
Unexpected error fetching FoxESS data: 'addressbook'

### ISSUE THREAD

**Issue by m4dh** [macxq/foxess-ha#95]
Logger: custom_components.foxess.sensor
Source: custom_components/foxess/sensor.py:143 
Integration: foxess (documentation, issues) 
First occurred: 12:03:19 (2 occurrences) 
Last logged: 12:08:29

Unexpected error fetching FoxESS data: 'addressbook'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 143, in async_update_data
    if int(allData["addressbook"]["result"]["status"]) == 1:
KeyError: 'addressbook'

HA CORE 2022.10.4

**Comment by rjhazeld** [comment]
Me too:

"This error originated from a custom integration.

Logger: custom_components.foxess.sensor
Source: custom_components/foxess/sensor.py:143
Integration: foxess (documentation, issues)
First occurred: 00:05:52 (10 occurrences)
Last logged: 11:07:38

Unexpected error fetching FoxESS data: 'addressbook'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 143, in async_update_data
    if int(allData["addressbook"]["result"]["status"]) == 1:
KeyError: 'addressbook'

also:
2022-11-26 00:05:52.262 ERROR (MainThread) [custom_components.foxess.sensor] Unable to get Addressbook data from FoxESS Cloud

There seems to be various spellings of addressbook (Addressbook, addressBook, AddressBook) I am not familiar enough with python to know if they are a problem or just variable naming.

It may or may not be coincidental that I am getting and error 'Entity currently unavailable sensor.foxess_bat_soc'.

**Comment by rjhazeld** [comment]
Mine appears to have started working properly this afternoon. maybe something to do with frequent timeouts on the Foxess cloud

**Comment by zoltandomokos** [comment]
Me too:

2022-12-03 16:10:37.049 ERROR (MainThread) [custom_components.foxess.sensor] Unexpected error fetching FoxESS data: Attempted to send an sync request with an AsyncClient instance.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/foxess/sensor.py", line 123, in async_update_data
    token = await authAndgetToken(hass, username, hashedPassword)
  File "/config/custom_components/foxess/sensor.py", line 194, in authAndgetToken
    await restAuth.async_update()
  File "/usr/src/homeassistant/homeassistant/components/rest/data.py", line 63, in async_update
    response = await self._async_client.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1711, in _send_single_request
    raise RuntimeError(
RuntimeError: Attempted to send an sync request with an AsyncClient instance.
2022-12-03 16:10:37.054 DEBUG (MainThread) [custom_components.foxess.sensor] Finished fetching FoxESS data in 0.035 seconds (success: False)
2022-12-03 16:10:37.055 ERROR (MainThread) [custom_components.foxess.sensor] FoxESS Cloud initializaction failed, fix error and restar ha

**Comment by macxq** [comment]
fixed in v0.16 thanks to @guba91
